version: "3.3"

services:
  localstack:
    image: localstack/localstack:0.12.15
    environment:
      - DEFAULT_REGION=eu-west-1
      - SERVICES=sqs,sns
      - PORT_WEB_UI=8400
      - DEBUG=1
    ports:
      - "4566-4599:4566-4599"
      - "8400:8400"
    volumes:
      - ./init_aws.sh:/docker-entrypoint-initaws.d/init_aws.sh
    healthcheck:
      test: awslocal sns list-subscriptions | grep "platform_resource_delete_sns"
      interval: 3s
      timeout: 10s
      retries: 15
